/* eslint-disable @stylistic/object-property-newline */

export const additionalAppLocales = {
  it: {
    common: { cancel: 'Annulla', close: 'Chiudi', save: 'Salva', saving: 'Salvataggio…', search: 'Cerca', settings: 'Impostazioni', remove: 'Rimuovi', add: 'Aggiungi', words: 'parole', characters: 'caratteri', localFirst: 'Prima locale' },
    navigation: { appearance: 'Aspetto', editor: 'Editor', vaults: 'Archivi', sync: 'Sincronizzazione', ai: 'IA', sites: 'Siti', import: 'Importa' },
    settings: { searchPlaceholder: 'Cerca in tutte le impostazioni', searchEmptyTitle: 'Nessuna impostazione trovata', searchEmptyDescription: 'Prova un’altra parola, funzione o controllo.', results: '{count} risultato | {count} risultati', language: 'Lingua', languageDescription: 'Usa una lingua ISO supportata o un pacchetto di traduzione installato.', systemLanguage: 'Lingua di sistema', colorMode: 'Modalità colore', colorModeDescription: 'Usa la variante chiara o scura del tema selezionato.', light: 'Chiaro', dark: 'Scuro', theme: 'Tema', themeDescription: 'Scegli la famiglia visiva usata in ElephantNote.', sidebarWidth: 'Larghezza barra laterale', sidebarWidthDescription: 'Ridimensiona la navigazione principale.' },
    note: { untitled: 'Senza titolo', titleLabel: 'Titolo della nota', addTag: 'Aggiungi tag', pin: 'Fissa nota', unpin: 'Rimuovi fissaggio', close: 'Chiudi nota', graph: 'Grafo', openGraph: 'Apri grafo', toggleTheme: 'Cambia tema', focusMode: 'Modalità concentrazione', findInNotes: 'Cerca nelle note' },
    excalidraw: { title: 'Excalidraw', drawingName: 'Nome del disegno', drawingPlaceholder: 'disegno', save: 'Salva disegno', cancel: 'Annulla disegno', saving: 'Salvataggio del disegno…', failedTitle: 'Impossibile aprire Excalidraw.', failedSave: 'Impossibile salvare il disegno.', failedInitialize: 'Impossibile inizializzare l’area di disegno.', localBadge: 'Salvato in questo archivio', hint: 'Disegna liberamente. La scena modificabile e l’anteprima PNG vengono salvate insieme.' },
    search: { open: 'Cerca note', shortcutHint: 'Cerca note con {shortcut}' }
  },
  pt: {
    common: { cancel: 'Cancelar', close: 'Fechar', save: 'Guardar', saving: 'A guardar…', search: 'Pesquisar', settings: 'Definições', remove: 'Remover', add: 'Adicionar', words: 'palavras', characters: 'caracteres', localFirst: 'Local primeiro' },
    navigation: { appearance: 'Aparência', editor: 'Editor', vaults: 'Cofres', sync: 'Sincronização', ai: 'IA', sites: 'Sites', import: 'Importar' },
    settings: { searchPlaceholder: 'Pesquisar em todas as definições', searchEmptyTitle: 'Nenhuma definição encontrada', searchEmptyDescription: 'Tente outra palavra, funcionalidade ou controlo.', results: '{count} resultado | {count} resultados', language: 'Idioma', languageDescription: 'Use qualquer idioma ISO suportado ou pacote de tradução instalado.', systemLanguage: 'Idioma do sistema', colorMode: 'Modo de cor', colorModeDescription: 'Use a variante clara ou escura do tema selecionado.', light: 'Claro', dark: 'Escuro', theme: 'Tema', themeDescription: 'Escolha a família visual usada no ElephantNote.', sidebarWidth: 'Largura da barra lateral', sidebarWidthDescription: 'Redimensione a navegação principal.' },
    note: { untitled: 'Sem título', titleLabel: 'Título da nota', addTag: 'Adicionar etiqueta', pin: 'Fixar nota', unpin: 'Desafixar nota', close: 'Fechar nota', graph: 'Grafo', openGraph: 'Abrir grafo', toggleTheme: 'Alternar tema', focusMode: 'Modo de foco', findInNotes: 'Pesquisar nas notas' },
    excalidraw: { title: 'Excalidraw', drawingName: 'Nome do desenho', drawingPlaceholder: 'desenho', save: 'Guardar desenho', cancel: 'Cancelar desenho', saving: 'A guardar desenho…', failedTitle: 'Não foi possível abrir o Excalidraw.', failedSave: 'Não foi possível guardar o desenho.', failedInitialize: 'Não foi possível iniciar a tela de desenho.', localBadge: 'Guardado neste cofre', hint: 'Desenhe livremente. A cena editável e a pré-visualização PNG são guardadas juntas.' },
    search: { open: 'Pesquisar notas', shortcutHint: 'Pesquisar notas com {shortcut}' }
  },
  nl: {
    common: { cancel: 'Annuleren', close: 'Sluiten', save: 'Opslaan', saving: 'Opslaan…', search: 'Zoeken', settings: 'Instellingen', remove: 'Verwijderen', add: 'Toevoegen', words: 'woorden', characters: 'tekens', localFirst: 'Lokaal eerst' },
    navigation: { appearance: 'Weergave', editor: 'Editor', vaults: 'Kluizen', sync: 'Synchronisatie', ai: 'AI', sites: 'Sites', import: 'Importeren' },
    settings: { searchPlaceholder: 'Alle instellingen doorzoeken', searchEmptyTitle: 'Geen instelling gevonden', searchEmptyDescription: 'Probeer een ander woord, functie of besturingselement.', results: '{count} resultaat | {count} resultaten', language: 'Taal', languageDescription: 'Gebruik elke ondersteunde ISO-taal of een geïnstalleerd vertaalpakket.', systemLanguage: 'Systeemtaal', colorMode: 'Kleurmodus', colorModeDescription: 'Gebruik de lichte of donkere variant van het gekozen thema.', light: 'Licht', dark: 'Donker', theme: 'Thema', themeDescription: 'Kies de visuele familie van ElephantNote.', sidebarWidth: 'Breedte zijbalk', sidebarWidthDescription: 'Pas de hoofdnavigatie aan.' },
    note: { untitled: 'Naamloos', titleLabel: 'Notitietitel', addTag: 'Tag toevoegen', pin: 'Notitie vastzetten', unpin: 'Notitie losmaken', close: 'Notitie sluiten', graph: 'Grafiek', openGraph: 'Grafiek openen', toggleTheme: 'Thema wisselen', focusMode: 'Focusmodus', findInNotes: 'Zoeken in notities' },
    excalidraw: { title: 'Excalidraw', drawingName: 'Naam van tekening', drawingPlaceholder: 'tekening', save: 'Tekening opslaan', cancel: 'Tekening annuleren', saving: 'Tekening opslaan…', failedTitle: 'Excalidraw kon niet worden geopend.', failedSave: 'De tekening kon niet worden opgeslagen.', failedInitialize: 'Het tekenvlak kon niet worden gestart.', localBadge: 'Opgeslagen in deze kluis', hint: 'Teken vrij. De bewerkbare scène en PNG-voorvertoning worden samen opgeslagen.' },
    search: { open: 'Notities zoeken', shortcutHint: 'Notities zoeken met {shortcut}' }
  },
  pl: {
    common: { cancel: 'Anuluj', close: 'Zamknij', save: 'Zapisz', saving: 'Zapisywanie…', search: 'Szukaj', settings: 'Ustawienia', remove: 'Usuń', add: 'Dodaj', words: 'słów', characters: 'znaków', localFirst: 'Najpierw lokalnie' },
    navigation: { appearance: 'Wygląd', editor: 'Edytor', vaults: 'Sejfy', sync: 'Synchronizacja', ai: 'AI', sites: 'Strony', import: 'Import' },
    settings: { searchPlaceholder: 'Szukaj we wszystkich ustawieniach', searchEmptyTitle: 'Nie znaleziono ustawienia', searchEmptyDescription: 'Spróbuj innego słowa, funkcji lub kontrolki.', results: '{count} wynik | {count} wyniki', language: 'Język', languageDescription: 'Użyj obsługiwanego języka ISO lub zainstalowanego pakietu tłumaczeń.', systemLanguage: 'Język systemu', colorMode: 'Tryb kolorów', colorModeDescription: 'Użyj jasnego lub ciemnego wariantu wybranego motywu.', light: 'Jasny', dark: 'Ciemny', theme: 'Motyw', themeDescription: 'Wybierz rodzinę wizualną ElephantNote.', sidebarWidth: 'Szerokość paska bocznego', sidebarWidthDescription: 'Zmień rozmiar głównej nawigacji.' },
    note: { untitled: 'Bez tytułu', titleLabel: 'Tytuł notatki', addTag: 'Dodaj tag', pin: 'Przypnij notatkę', unpin: 'Odepnij notatkę', close: 'Zamknij notatkę', graph: 'Graf', openGraph: 'Otwórz graf', toggleTheme: 'Zmień motyw', focusMode: 'Tryb skupienia', findInNotes: 'Szukaj w notatkach' },
    excalidraw: { title: 'Excalidraw', drawingName: 'Nazwa rysunku', drawingPlaceholder: 'rysunek', save: 'Zapisz rysunek', cancel: 'Anuluj rysunek', saving: 'Zapisywanie rysunku…', failedTitle: 'Nie udało się otworzyć Excalidraw.', failedSave: 'Nie udało się zapisać rysunku.', failedInitialize: 'Nie udało się uruchomić obszaru rysowania.', localBadge: 'Zapisano w tym sejfie', hint: 'Rysuj swobodnie. Edytowalna scena i podgląd PNG są zapisywane razem.' },
    search: { open: 'Szukaj notatek', shortcutHint: 'Szukaj notatek za pomocą {shortcut}' }
  },
  ru: {
    common: { cancel: 'Отмена', close: 'Закрыть', save: 'Сохранить', saving: 'Сохранение…', search: 'Поиск', settings: 'Настройки', remove: 'Удалить', add: 'Добавить', words: 'слов', characters: 'символов', localFirst: 'Сначала локально' },
    navigation: { appearance: 'Оформление', editor: 'Редактор', vaults: 'Хранилища', sync: 'Синхронизация', ai: 'ИИ', sites: 'Сайты', import: 'Импорт' },
    settings: { searchPlaceholder: 'Поиск по всем настройкам', searchEmptyTitle: 'Настройка не найдена', searchEmptyDescription: 'Попробуйте другое слово, функцию или элемент управления.', results: '{count} результат | {count} результатов', language: 'Язык', languageDescription: 'Используйте поддерживаемый язык ISO или установленный пакет перевода.', systemLanguage: 'Язык системы', colorMode: 'Цветовой режим', colorModeDescription: 'Используйте светлый или тёмный вариант выбранной темы.', light: 'Светлый', dark: 'Тёмный', theme: 'Тема', themeDescription: 'Выберите визуальное оформление ElephantNote.', sidebarWidth: 'Ширина боковой панели', sidebarWidthDescription: 'Измените размер основной навигации.' },
    note: { untitled: 'Без названия', titleLabel: 'Название заметки', addTag: 'Добавить тег', pin: 'Закрепить заметку', unpin: 'Открепить заметку', close: 'Закрыть заметку', graph: 'Граф', openGraph: 'Открыть граф', toggleTheme: 'Сменить тему', focusMode: 'Режим фокусировки', findInNotes: 'Искать в заметках' },
    excalidraw: { title: 'Excalidraw', drawingName: 'Название рисунка', drawingPlaceholder: 'рисунок', save: 'Сохранить рисунок', cancel: 'Отменить рисунок', saving: 'Сохранение рисунка…', failedTitle: 'Не удалось открыть Excalidraw.', failedSave: 'Не удалось сохранить рисунок.', failedInitialize: 'Не удалось запустить холст.', localBadge: 'Сохранено в этом хранилище', hint: 'Рисуйте свободно. Редактируемая сцена и PNG-превью сохраняются вместе.' },
    search: { open: 'Искать заметки', shortcutHint: 'Искать заметки с помощью {shortcut}' }
  },
  uk: {
    common: { cancel: 'Скасувати', close: 'Закрити', save: 'Зберегти', saving: 'Збереження…', search: 'Пошук', settings: 'Налаштування', remove: 'Видалити', add: 'Додати', words: 'слів', characters: 'символів', localFirst: 'Спочатку локально' },
    navigation: { appearance: 'Вигляд', editor: 'Редактор', vaults: 'Сховища', sync: 'Синхронізація', ai: 'ШІ', sites: 'Сайти', import: 'Імпорт' },
    settings: { searchPlaceholder: 'Пошук у всіх налаштуваннях', searchEmptyTitle: 'Налаштування не знайдено', searchEmptyDescription: 'Спробуйте інше слово, функцію або елемент керування.', results: '{count} результат | {count} результатів', language: 'Мова', languageDescription: 'Використовуйте підтримувану мову ISO або встановлений пакет перекладу.', systemLanguage: 'Мова системи', colorMode: 'Колірний режим', colorModeDescription: 'Використовуйте світлий або темний варіант вибраної теми.', light: 'Світлий', dark: 'Темний', theme: 'Тема', themeDescription: 'Виберіть візуальну тему ElephantNote.', sidebarWidth: 'Ширина бічної панелі', sidebarWidthDescription: 'Змініть розмір основної навігації.' },
    note: { untitled: 'Без назви', titleLabel: 'Назва нотатки', addTag: 'Додати тег', pin: 'Закріпити нотатку', unpin: 'Відкріпити нотатку', close: 'Закрити нотатку', graph: 'Граф', openGraph: 'Відкрити граф', toggleTheme: 'Змінити тему', focusMode: 'Режим фокусування', findInNotes: 'Шукати в нотатках' },
    excalidraw: { title: 'Excalidraw', drawingName: 'Назва малюнка', drawingPlaceholder: 'малюнок', save: 'Зберегти малюнок', cancel: 'Скасувати малюнок', saving: 'Збереження малюнка…', failedTitle: 'Не вдалося відкрити Excalidraw.', failedSave: 'Не вдалося зберегти малюнок.', failedInitialize: 'Не вдалося запустити полотно.', localBadge: 'Збережено в цьому сховищі', hint: 'Малюйте вільно. Редагована сцена та PNG-перегляд зберігаються разом.' },
    search: { open: 'Шукати нотатки', shortcutHint: 'Шукати нотатки за допомогою {shortcut}' }
  },
  tr: {
    common: { cancel: 'İptal', close: 'Kapat', save: 'Kaydet', saving: 'Kaydediliyor…', search: 'Ara', settings: 'Ayarlar', remove: 'Kaldır', add: 'Ekle', words: 'kelime', characters: 'karakter', localFirst: 'Önce yerel' },
    navigation: { appearance: 'Görünüm', editor: 'Düzenleyici', vaults: 'Kasalar', sync: 'Eşitleme', ai: 'Yapay zekâ', sites: 'Siteler', import: 'İçe aktar' },
    settings: { searchPlaceholder: 'Tüm ayarlarda ara', searchEmptyTitle: 'Ayar bulunamadı', searchEmptyDescription: 'Başka bir kelime, özellik veya denetim deneyin.', results: '{count} sonuç | {count} sonuç', language: 'Dil', languageDescription: 'Desteklenen herhangi bir ISO dilini veya yüklü çeviri paketini kullanın.', systemLanguage: 'Sistem dili', colorMode: 'Renk modu', colorModeDescription: 'Seçili temanın açık veya koyu sürümünü kullanın.', light: 'Açık', dark: 'Koyu', theme: 'Tema', themeDescription: 'ElephantNote için görsel aileyi seçin.', sidebarWidth: 'Kenar çubuğu genişliği', sidebarWidthDescription: 'Ana gezinmeyi yeniden boyutlandırın.' },
    note: { untitled: 'Başlıksız', titleLabel: 'Not başlığı', addTag: 'Etiket ekle', pin: 'Notu sabitle', unpin: 'Sabitlemeyi kaldır', close: 'Notu kapat', graph: 'Grafik', openGraph: 'Grafiği aç', toggleTheme: 'Temayı değiştir', focusMode: 'Odak modu', findInNotes: 'Notlarda ara' },
    excalidraw: { title: 'Excalidraw', drawingName: 'Çizim adı', drawingPlaceholder: 'çizim', save: 'Çizimi kaydet', cancel: 'Çizimi iptal et', saving: 'Çizim kaydediliyor…', failedTitle: 'Excalidraw açılamadı.', failedSave: 'Çizim kaydedilemedi.', failedInitialize: 'Çizim alanı başlatılamadı.', localBadge: 'Bu kasaya kaydedildi', hint: 'Özgürce çizin. Düzenlenebilir sahne ve PNG önizlemesi birlikte kaydedilir.' },
    search: { open: 'Notlarda ara', shortcutHint: '{shortcut} ile notlarda ara' }
  },
  ja: {
    common: { cancel: 'キャンセル', close: '閉じる', save: '保存', saving: '保存中…', search: '検索', settings: '設定', remove: '削除', add: '追加', words: '単語', characters: '文字', localFirst: 'ローカル優先' },
    navigation: { appearance: '外観', editor: 'エディター', vaults: '保管庫', sync: '同期', ai: 'AI', sites: 'サイト', import: 'インポート' },
    settings: { searchPlaceholder: 'すべての設定を検索', searchEmptyTitle: '設定が見つかりません', searchEmptyDescription: '別の単語、機能、または操作を試してください。', results: '{count} 件', language: '言語', languageDescription: '対応する ISO 言語またはインストール済みの翻訳パックを使用します。', systemLanguage: 'システム言語', colorMode: 'カラーモード', colorModeDescription: '選択したテーマのライトまたはダーク版を使用します。', light: 'ライト', dark: 'ダーク', theme: 'テーマ', themeDescription: 'ElephantNote で使用する外観を選択します。', sidebarWidth: 'サイドバーの幅', sidebarWidthDescription: 'メインナビゲーションの幅を変更します。' },
    note: { untitled: '無題', titleLabel: 'ノートのタイトル', addTag: 'タグを追加', pin: 'ノートを固定', unpin: '固定を解除', close: 'ノートを閉じる', graph: 'グラフ', openGraph: 'グラフを開く', toggleTheme: 'テーマを切り替え', focusMode: '集中モード', findInNotes: 'ノートを検索' },
    excalidraw: { title: 'Excalidraw', drawingName: '図面名', drawingPlaceholder: '図面', save: '図面を保存', cancel: '図面をキャンセル', saving: '図面を保存中…', failedTitle: 'Excalidraw を開けませんでした。', failedSave: '図面を保存できませんでした。', failedInitialize: '描画キャンバスを初期化できませんでした。', localBadge: 'この保管庫に保存済み', hint: '自由に描画できます。編集可能なシーンと PNG プレビューは一緒に保存されます。' },
    search: { open: 'ノートを検索', shortcutHint: '{shortcut} でノートを検索' }
  },
  ko: {
    common: { cancel: '취소', close: '닫기', save: '저장', saving: '저장 중…', search: '검색', settings: '설정', remove: '제거', add: '추가', words: '단어', characters: '문자', localFirst: '로컬 우선' },
    navigation: { appearance: '모양', editor: '편집기', vaults: '보관함', sync: '동기화', ai: 'AI', sites: '사이트', import: '가져오기' },
    settings: { searchPlaceholder: '모든 설정 검색', searchEmptyTitle: '설정을 찾을 수 없음', searchEmptyDescription: '다른 단어, 기능 또는 제어 항목을 사용해 보세요.', results: '{count}개 결과', language: '언어', languageDescription: '지원되는 ISO 언어 또는 설치된 번역 팩을 사용합니다.', systemLanguage: '시스템 언어', colorMode: '색상 모드', colorModeDescription: '선택한 테마의 밝은 또는 어두운 버전을 사용합니다.', light: '밝게', dark: '어둡게', theme: '테마', themeDescription: 'ElephantNote에서 사용할 시각적 스타일을 선택합니다.', sidebarWidth: '사이드바 너비', sidebarWidthDescription: '기본 탐색 영역의 크기를 조정합니다.' },
    note: { untitled: '제목 없음', titleLabel: '노트 제목', addTag: '태그 추가', pin: '노트 고정', unpin: '고정 해제', close: '노트 닫기', graph: '그래프', openGraph: '그래프 열기', toggleTheme: '테마 전환', focusMode: '집중 모드', findInNotes: '노트 검색' },
    excalidraw: { title: 'Excalidraw', drawingName: '그림 이름', drawingPlaceholder: '그림', save: '그림 저장', cancel: '그림 취소', saving: '그림 저장 중…', failedTitle: 'Excalidraw를 열 수 없습니다.', failedSave: '그림을 저장할 수 없습니다.', failedInitialize: '그리기 캔버스를 초기화할 수 없습니다.', localBadge: '이 보관함에 저장됨', hint: '자유롭게 그리세요. 편집 가능한 장면과 PNG 미리보기가 함께 저장됩니다.' },
    search: { open: '노트 검색', shortcutHint: '{shortcut}으로 노트 검색' }
  },
  'zh-CN': {
    common: { cancel: '取消', close: '关闭', save: '保存', saving: '正在保存…', search: '搜索', settings: '设置', remove: '移除', add: '添加', words: '字词', characters: '字符', localFirst: '本地优先' },
    navigation: { appearance: '外观', editor: '编辑器', vaults: '仓库', sync: '同步', ai: 'AI', sites: '站点', import: '导入' },
    settings: { searchPlaceholder: '搜索所有设置', searchEmptyTitle: '未找到设置', searchEmptyDescription: '请尝试其他词语、功能或控件。', results: '{count} 个结果', language: '语言', languageDescription: '使用受支持的 ISO 语言或已安装的翻译包。', systemLanguage: '系统语言', colorMode: '颜色模式', colorModeDescription: '使用所选主题的浅色或深色版本。', light: '浅色', dark: '深色', theme: '主题', themeDescription: '选择 ElephantNote 使用的视觉风格。', sidebarWidth: '侧边栏宽度', sidebarWidthDescription: '调整主导航栏大小。' },
    note: { untitled: '无标题', titleLabel: '笔记标题', addTag: '添加标签', pin: '固定笔记', unpin: '取消固定', close: '关闭笔记', graph: '关系图', openGraph: '打开关系图', toggleTheme: '切换主题', focusMode: '专注模式', findInNotes: '搜索笔记' },
    excalidraw: { title: 'Excalidraw', drawingName: '绘图名称', drawingPlaceholder: '绘图', save: '保存绘图', cancel: '取消绘图', saving: '正在保存绘图…', failedTitle: '无法打开 Excalidraw。', failedSave: '无法保存绘图。', failedInitialize: '无法初始化绘图画布。', localBadge: '已保存到此仓库', hint: '自由绘制。可编辑场景和 PNG 预览会一起保存。' },
    search: { open: '搜索笔记', shortcutHint: '使用 {shortcut} 搜索笔记' }
  },
  'zh-TW': {
    common: { cancel: '取消', close: '關閉', save: '儲存', saving: '正在儲存…', search: '搜尋', settings: '設定', remove: '移除', add: '新增', words: '字詞', characters: '字元', localFirst: '本機優先' },
    navigation: { appearance: '外觀', editor: '編輯器', vaults: '資料庫', sync: '同步', ai: 'AI', sites: '網站', import: '匯入' },
    settings: { searchPlaceholder: '搜尋所有設定', searchEmptyTitle: '找不到設定', searchEmptyDescription: '請嘗試其他詞語、功能或控制項。', results: '{count} 個結果', language: '語言', languageDescription: '使用支援的 ISO 語言或已安裝的翻譯套件。', systemLanguage: '系統語言', colorMode: '色彩模式', colorModeDescription: '使用所選主題的淺色或深色版本。', light: '淺色', dark: '深色', theme: '主題', themeDescription: '選擇 ElephantNote 使用的視覺風格。', sidebarWidth: '側邊欄寬度', sidebarWidthDescription: '調整主導覽列大小。' },
    note: { untitled: '未命名', titleLabel: '筆記標題', addTag: '新增標籤', pin: '釘選筆記', unpin: '取消釘選', close: '關閉筆記', graph: '關聯圖', openGraph: '開啟關聯圖', toggleTheme: '切換主題', focusMode: '專注模式', findInNotes: '搜尋筆記' },
    excalidraw: { title: 'Excalidraw', drawingName: '繪圖名稱', drawingPlaceholder: '繪圖', save: '儲存繪圖', cancel: '取消繪圖', saving: '正在儲存繪圖…', failedTitle: '無法開啟 Excalidraw。', failedSave: '無法儲存繪圖。', failedInitialize: '無法初始化繪圖畫布。', localBadge: '已儲存到此資料庫', hint: '自由繪製。可編輯場景與 PNG 預覽會一起儲存。' },
    search: { open: '搜尋筆記', shortcutHint: '使用 {shortcut} 搜尋筆記' }
  },
  ar: {
    common: { cancel: 'إلغاء', close: 'إغلاق', save: 'حفظ', saving: 'جارٍ الحفظ…', search: 'بحث', settings: 'الإعدادات', remove: 'إزالة', add: 'إضافة', words: 'كلمات', characters: 'أحرف', localFirst: 'محلي أولاً' },
    navigation: { appearance: 'المظهر', editor: 'المحرر', vaults: 'الخزائن', sync: 'المزامنة', ai: 'الذكاء الاصطناعي', sites: 'المواقع', import: 'استيراد' },
    settings: { searchPlaceholder: 'البحث في جميع الإعدادات', searchEmptyTitle: 'لم يتم العثور على إعداد', searchEmptyDescription: 'جرّب كلمة أو ميزة أو عنصر تحكم آخر.', results: '{count} نتيجة', language: 'اللغة', languageDescription: 'استخدم أي لغة ISO مدعومة أو حزمة ترجمة مثبتة.', systemLanguage: 'لغة النظام', colorMode: 'وضع الألوان', colorModeDescription: 'استخدم النسخة الفاتحة أو الداكنة من السمة المحددة.', light: 'فاتح', dark: 'داكن', theme: 'السمة', themeDescription: 'اختر النمط المرئي المستخدم في ElephantNote.', sidebarWidth: 'عرض الشريط الجانبي', sidebarWidthDescription: 'غيّر حجم شريط التنقل الرئيسي.' },
    note: { untitled: 'بلا عنوان', titleLabel: 'عنوان الملاحظة', addTag: 'إضافة وسم', pin: 'تثبيت الملاحظة', unpin: 'إلغاء تثبيت الملاحظة', close: 'إغلاق الملاحظة', graph: 'الرسم البياني', openGraph: 'فتح الرسم البياني', toggleTheme: 'تبديل السمة', focusMode: 'وضع التركيز', findInNotes: 'البحث في الملاحظات' },
    excalidraw: { title: 'Excalidraw', drawingName: 'اسم الرسم', drawingPlaceholder: 'رسم', save: 'حفظ الرسم', cancel: 'إلغاء الرسم', saving: 'جارٍ حفظ الرسم…', failedTitle: 'تعذر فتح Excalidraw.', failedSave: 'تعذر حفظ الرسم.', failedInitialize: 'تعذر تهيئة لوحة الرسم.', localBadge: 'محفوظ في هذه الخزنة', hint: 'ارسم بحرية. يتم حفظ المشهد القابل للتحرير ومعاينة PNG معًا.' },
    search: { open: 'البحث في الملاحظات', shortcutHint: 'البحث في الملاحظات باستخدام {shortcut}' }
  }
}
