export const MUYA_DEFAULT_OPTION = Object.freeze({
  fontSize: 16,
  lineHeight: 1.6,
  focusMode: false,
  markdown: '',
  trimUnnecessaryCodeBlockEmptyLines: false,
  preferLooseListItem: true,
  autoPairBracket: true,
  autoPairMarkdownSyntax: true,
  autoPairQuote: true,
  bulletListMarker: '-',
  orderListDelimiter: '.',
  tabSize: 4,
  codeBlockLineNumbers: false,
  listIndentation: 1,
  frontmatterType: '-',
  sequenceTheme: 'hand',
  mermaidTheme: 'default',
  vegaTheme: 'latimes',
  hideQuickInsertHint: false,
  quickInsertTrigger: '/',
  elephantnoteCommandHandler: null,
  canEditExcalidrawImage: null,
  hideLinkPopup: false,
  autoCheck: false,
  spellcheckEnabled: false,
  imageAction: null,
  imagePathPicker: null,
  openImageWithExternalTool: null,
  clipboardFilePath: () => {},
  imagePathAutoComplete: () => [],
  superSubScript: false,
  footnote: false,
  isGitlabCompatibilityEnabled: false,
  disableHtml: true,
  experimentalRustEditor: null
})
