self.elephantAddon = {
  activate(api) {
    return api.commands.register({
      id: 'com.elephantnote.examples.platform-proof.run',
      title: 'Run addon platform proof',
      description: 'Exercise the isolated Worker, app broker, private storage and scoped note read/write APIs.',
      async run() {
        const app = await api.app.info()
        const previousCount = Number(await api.storage.get('runCount')) || 0
        const runCount = previousCount + 1
        const executedAt = new Date().toISOString()
        const path = 'Addon Proof/External Addon Platform Proof.md'
        const marker = `ELEPHANT_ADDON_PROOF:${runCount}:${executedAt}`

        await api.storage.set('runCount', runCount)
        await api.storage.set('lastRun', { runCount, executedAt, app })

        const markdown = [
          '# External Addon Platform Proof',
          '',
          'This note was generated by a community addon running inside the ElephantNote JavaScript Worker runtime.',
          '',
          '## Verified capabilities',
          '',
          '- [x] External addon package loaded from `.elephantnote/addons/packages`',
          '- [x] Isolated Worker activation',
          '- [x] Command registration and execution',
          '- [x] Brokered `app.info` call',
          '- [x] Private addon storage read/write',
          '- [x] Scoped Markdown note write',
          '- [x] Scoped Markdown note read-back',
          '',
          '## Runtime result',
          '',
          `- ElephantNote version: ${app.version}`,
          `- Addon API version: ${app.addonApiVersion}`,
          `- Successful proof run: ${runCount}`,
          `- Executed at: ${executedAt}`,
          '',
          '## Verification marker',
          '',
          `\`${marker}\``,
          ''
        ].join('\n')

        await api.notes.write(path, markdown)
        const readBack = await api.notes.read(path)
        const storage = await api.storage.entries()
        const verified = readBack.content === markdown && storage.runCount === runCount

        if (!verified) throw new Error('Addon platform proof failed during note read-back or storage verification')

        return {
          verified,
          path,
          runCount,
          executedAt,
          appVersion: app.version,
          addonApiVersion: app.addonApiVersion,
          marker
        }
      }
    })
  }
}
