name: final_editor
description: Final Web Editor for C-Editor with GitHub Pages deployment
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.2.7
  idb_shim: ^2.4.1+1
  js: ^0.7.1
  web: ^1.0.0
  file_picker: ^8.0.0+1
  
  # UI
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  golden_toolkit: ^0.15.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/core/
    - assets/icons/
    - examples/fixtures/
  
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700