name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  review:
    if: github.event_name == 'pull_request' || contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run Claude Code Review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: |
            Review the changes in this C markdown editor project. Focus on:
            
            1. **Memory Safety**: Check for potential memory leaks, buffer overflows, and proper malloc/free usage
            2. **Code Quality**: Examine function design, variable naming, and overall structure
            3. **Bug Detection**: Look for logical errors, edge cases, and potential crashes
            4. **Performance**: Identify performance bottlenecks or inefficient algorithms
            5. **Standards Compliance**: Ensure C11 compliance and consistent coding style
            6. **Testing**: Verify that changes are properly tested
            
            For this markdown editor project, pay special attention to:
            - Markdown parsing logic and edge cases
            - JSON serialization/deserialization
            - Table parsing and formatting
            - Memory management in text processing
            - Cross-platform compatibility (Windows, macOS, Linux)
            
            Provide specific, actionable feedback with code examples where helpful.